services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: volunteer-hub-db
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: ~
